spring:
  application:
    name: support-management-system-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    open-in-view: false

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: support-management-system-api
      audience: support-management-system-api-client
      access-token-expiration: 900000
      refresh-token-expiration: 2592000000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
