spring:
  application:
    name: support-management-system-api
  datasource:
    url: jdbc:postgresql://localhost:5432/support_management_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
